server:
   port: 5000
   
spring:
   data:
      mongodb:
         uri: mongodb+srv://user:example@parkingdb-iqc1m.mongodb.net/testDB?retryWrites=true&w=majority
         #host: localhost
         #port: 27017
         #username: root
         #database: admin
         #password: example

swagger:
   enabled: true
   title: 'Parking API Services'
   description: 'API for Parking services'
   version: 2.0.7
   security:
      enabled: false